version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - balles

- package-ecosystem: npm
  directory: "examples/create-react-diagrams-ts"
  schedule:
    interval: monthly
  ignore:
      - dependency-name: "*"
  open-pull-requests-limit: 1
  reviewers:
  - balles
