name: Publish new package versions

on:
  push:
    branches: [ main ]

jobs:
  publish-package:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Add npm credentials
      run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
      env:
          NPM_TOKEN: ${{ secrets.NPM_DIAGRAMS_BOT_TOKEN }}
    - name: Install dependencies
      run: yarn
    - name: Build TS
      run: yarn build
    - uses: oleksiyrudenko/gha-git-credentials@34343d93d6e53cd85bbe557d83c722a3de1c15ef
      with:
        token: '${{ secrets.GITHUB_TOKEN }}'
    - name: Publish packages
      run: yarn publish-packages