name: Publish new package versions

on:
  push:
    branches: [ main ]

jobs:
  check-code:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install dependencies
      run: yarn
    - name: Build TS
      run: yarn build
    - name: Run tests
      run: yarn test
    - name: Publish packages
      run: yarn publish-packages