name: create-pr-for-new-diagrams
on: workflow_dispatch
jobs:

  create-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check for change
        run: |
          curl https://api.github.com/repos/mingrammer/diagrams/contents/
          DIAGRAMS_COMMIT=$(curl https://api.github.com/repos/mingrammer/diagrams/contents/ | jq '.[] | select(.name=="resources") | .sha')
          CURRENT_DIAGRAMS_COMMIT=$(cat package.json | jq '."diagrams-python-sha"')
          echo "::set-output name=diagrams-sha::$DIAGRAMS_COMMIT"
          if [ $DIAGRAMS_COMMIT != $CURRENT_DIAGRAMS_COMMIT ]; then
          echo "::set-output name=changed::true"
          fi
        id: check-for-change
      - run:  echo "Diagrams sh is ${{steps.check-for-change.diagrams-sha}} "
      - run: echo "Changed is set, this job runs."
        if: steps.check-for-change.changed
      # - name: Use Node.js
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: "14.x"
      # - run: yarn 
      # - run: git clone https://github.com/mingrammer/diagrams.git diagrams-python
      # - run: $DIAGRAMS_COMMIT dfd8e0a52c8c4d1c3ce95dc7161c23bb2eaf0acb yarn generate-providers