name: create-pr-for-new-diagrams
on: 
  workflow_dispatch
jobs: 
  create-pr:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: node -v